// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _9p2.Models;

#nullable disable

namespace _9p2.Migrations
{
    [DbContext(typeof(mydb))]
    [Migration("20240506175830_update img dataType")]
    partial class updateimgdataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_9p2.Models.category", b =>
                {
                    b.Property<int>("cat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cat_id"));

                    b.Property<string>("cat_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cat_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("_9p2.Models.product", b =>
                {
                    b.Property<int>("pro_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pro_id"));

                    b.Property<int>("categorycat_id")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("pro_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pro_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.HasKey("pro_id");

                    b.HasIndex("categorycat_id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("_9p2.Models.tbl_login", b =>
                {
                    b.Property<int>("login_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("login_id"));

                    b.Property<string>("login_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login_pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("login_id");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("_9p2.Models.product", b =>
                {
                    b.HasOne("_9p2.Models.category", "category")
                        .WithMany()
                        .HasForeignKey("categorycat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
